template = ""
rev_id = 3
template_sha = "50f983ed6da8e78c9c3344a18d6a46e3f843236c"

[replacements]
__LICENSE__ = "proprietary"
__UND2C_SRC__ = "smj"
__UND2C_TRG__ = "nb"
__UNDEFINED_SOURCE__ = "Lule Sámi"
__UNDEFINED_TARGET__ = "Norwegian Bokmål"
__UND_SRC__ = "smj"
__UND_TRG__ = "nob"
