template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "proprietary"
__UND2C_SRC__ = "smj"
__UND2C_TRG__ = "nb"
__UNDEFINED_SOURCE__ = "Lule Sámi"
__UNDEFINED_TARGET__ = "Norwegian Bokmål"
__UND_SRC__ = "smj"
__UND_TRG__ = "nob"
